# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app

  target 'app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end

